### ISSUE TITLE
Question about Sink+Sliding Window

### ISSUE THREAD

**Issue by namespace-Pt** [mit-han-lab/duo-attention#3]
Thanks for your great work! I have a small question regarding the sink+sliding window implementation.

I think the attention matrix in Figure 5 is not standard sink + sliding window, instead, it is chunk-wise sink + causal: in each chunk, the `i`-th token can attend to one more token than `i-1`-th token. 

To my understanding, you are doing this because flash_attn does not support sink+sliding window yet and you do not want to implement a customized kernel. Do you think there would be a difference between the current implementation against the standard sink+sliding window kernel (where each token attends to exactly the same number of recent tokens)?

**Comment by Guangxuan-Xiao** [comment]
Thank you for your kind words and for the insightful question. Yes, your understanding is correct. In our design, we did not use specialized kernels for pre-filling, which is why the attention behavior appears as you described. I haven't run experiments on the specific settings you mentioned, but I would hypothesize that the accuracy results would be quite similar to those of an exact sink+sliding window implementation.
